# labels auto assigned to PR, keep in sync with labels.yml
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["docs/**", "*.md", "LICENSE"]
markdown:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["docs/**", "*.md", "LICENSE"]
dependencies:
  - any:
      - head-branch: ["^dependabot"]
shell:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/*.sh"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [".github/workflows/*", ".github/workflows/**/*"]
git_hooks:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["githooks/**"]
